baseURL = "https://pocas-alt.github.io/pro-implant-how-to/"
languageCode = 'en-us'
title = 'How-To Guides'
theme = 'hugo-book'

[params]
  BookTheme = 'light'
  BookSection = '*'   # <<< ADD THIS LINE

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.sidebar]]
identifier = "howto"
name = "How-To Guides"
url = "/"
weight = 1

[[menu.sidebar]]
identifier = "microsoft-business-central"
parent = "howto"
name = "Microsoft Business Central"
url = "/microsoft-business-central/"
weight = 2

[[menu.sidebar]]
parent = "microsoft-business-central"
name = "KIO"
url = "/microsoft-business-central/kio/"
weight = 1

[[menu.sidebar]]
parent = "microsoft-business-central"
name = "KPO"
url = "/microsoft-business-central/kpo/"
weight = 2

[[menu.sidebar]]
parent = "howto"
name = "Pro-implant"
url = "/pro-implant/"
weight = 3

[[menu.sidebar]]
parent = "howto"
name = "Amosas"
url = "/amosas/"
weight = 4

[[menu.sidebar]]
parent = "howto"
name = "Dental"
url = "/dental/"
weight = 5

[[menu.sidebar]]
parent = "howto"
name = "Romexis"
url = "/romexis/"
weight = 6